# Generated by Django 4.1.2 on 2022-11-05 14:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('iin_num', models.CharField(max_length=12)),
                ('full_name', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=2)),
                ('emergency_cont_num', models.CharField(max_length=11)),
                ('contact_num', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=20)),
                ('registration_date', models.DateField()),
                ('password', models.CharField(max_length=30)),
                ('marital_status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Medical_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('iin_num', models.CharField(max_length=12)),
                ('full_name', models.CharField(max_length=50)),
                ('contact_num', models.CharField(max_length=11)),
                ('experience', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('category', models.CharField(max_length=15)),
                ('price_of_appointment', models.IntegerField()),
                ('schedule_details', models.CharField(max_length=100)),
                ('education_degree', models.CharField(max_length=10)),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('address', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.department')),
                ('specialization_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.specialization_details')),
            ],
        ),
    ]
