# Generated by Django 4.1.2 on 2022-11-24 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_staff',
            name='department_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.department'),
        ),
        migrations.AlterField(
            model_name='medical_staff',
            name='specialization_details_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.specialization_details'),
        ),
    ]
